# Supported: GCC, CLANG, ICX, NVCC, HIP
TOOLCHAIN ?= GCC
ENABLE_OPENMP ?= false
ENABLE_LIKWID ?= false

#Feature options
OPTIONS +=  -DARRAY_ALIGNMENT=64
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
